# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    outputs:
      output1: ${{ steps.artifact.outputs.artifact-url }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        python -m venv .venv
        .venv/Scripts/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Lint with flake8
      run: |
        .venv/Scripts/deactivate
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .venv
    - name: Test with pytest
      run: |
        .venv/Scripts/activate
        pytest --doctest-modules --junitxml=junit/test-results.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
          name: pytest-results
          path: junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Build with pyinstaller
      run: |
        .venv/Scripts/activate
        pyinstaller excel2zugferd.py --noconsole --add-data _internal/Fonts:Fonts --add-data ./.venv/Lib/site-packages/drafthorse/schema:drafthorse/schema --noconfirm

    - name: Deploy artifacts
      uses: actions/upload-artifact@v4
      id: artifact
      with:
          name: excel2zugferd
          path: dist/excel2zugferd*
          if-no-files-found: error


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    concurrency: release
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Semantic Release
      uses: thenativeweb/get-next-version@2.6.1
      with:
        prefix: 'v'
      id: get_next_version
    - name: Create new tag
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION
    - name: Create Release
      id: create_release
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_next_version.outputs.version }}
        release_name: Version ${{ steps.get_next_version.outputs.version }}
        draft: false
        prerelease: true
    - name: Get Asset
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        curl -X POST -H "Authorization: Bearer "${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary "${{needs.build.outputs.output1}}"
    - name: Upload Release Asset
      id: upload-release-asset 
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./excel2zugferd.zip
          asset_name: excel2zugferd.zip
          asset_content_type: application/zip
#        gh release create $NEXT_VERSION $OUTPUT1

